# Site settings
title: 龍ジラ
email: ryuutei.at.work@gmail.com
description: "WUBALUBADUBDUB‼"
#baseurl: "" # the subpath of your site, e.g. /blog
#url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: Ryuutei
github_username:  Ryuutei

timezone: Europe/Paris

# Build settings
encoding: utf-8
highlighter: rouge
show_drafts: nil
future: true
